back-app:
  pagination:
    max-hits-per-page: 5
front-app:
  expiration-track-range: 30
spring:
  devtools:
    livereload:
      enabled:
        true
  datasource:
    url: jdbc:mysql://localhost:33061/stock_db
    username: root
    password: bar
    hikari:
      allow-pool-suspension: true
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQLDialect
