spring:
  datasource:
    url: jdbc:mysql://localhost:33060/stock-db
    username: root
    password: bar
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
